### ISSUE TITLE
[BUG] DiscordChat ERROR JDA - One of the EventListeners had an uncaught exception

### ISSUE THREAD

**Issue by Fargus5** [DevLan-Support/arvan#14]
```
[14:26:58]: [INFO] [DiscordChat] Enabling DiscordChat v1.6
[14:26:58]: [INFO] [DiscordChat] Loading DiscordChat v1.6 for Spigot 1.16.3-R0.1-SNAPSHOT
[14:26:59]: [WARN] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
[14:26:59]: [WARN] SLF4J: Defaulting to no-operation (NOP) logger implementation
[14:26:59]: [WARN] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[14:26:59]: [WARN] SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
[14:26:59]: [WARN] SLF4J: Defaulting to no-operation MDCAdapter implementation.
[14:26:59]: [WARN] SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[14:26:59]: [WARN] [Server thread] INFO JDA - Login Successful!
[14:26:59]: [WARN] [JDA MainWS-WriteThread] INFO WebSocketClient - Connected to WebSocket
[14:27:00]: [WARN] [JDA MainWS-ReadThread] INFO JDA - Finished Loading!
[14:27:00]: [INFO] [DiscordChat] Successfully linked to Discord server 'DevLan#「」arvan-chat'!
[14:27:00]: [INFO] [PlugMan] DiscordChat has been reloaded.
```

```
[14:23:55] [JDA MainWS-ReadThread/WARN]: [JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception
[14:23:55] [JDA MainWS-ReadThread/WARN]: java.lang.NullPointerException
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.api.discord.DiscordBot.onGuildMessageReceived(DiscordBot.java:61)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:398)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:82)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:69)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:150)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:948)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:835)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:813)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:986)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
[14:23:55] [JDA MainWS-ReadThread/WARN]: at me.koenn.serverchat.lib.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

**Comment by AykaTV** [comment]
Also experiencing this issue on JDK-8, Server 1.16.3

Only occurs when someone sends a message from Discord, but isn't the server owner. I can seem to send messages fine, but when someone else does it generates the Error.

[JDA MainWS-ReadThread] ERROR JDA - One of the EventListeners had an uncaught exception[2020-11-11 22:58:52] [WARN]: java.lang.NullPointerException[2020-11-11 22:58:52] [WARN]: at me.koenn.serverchat.api.discord.DiscordBot.onGuildMessageReceived(DiscordBot.java:61)

**Comment by Fargus5** [comment]
Problem has been Fixed with recoding the entiere plugin.
