### ISSUE TITLE
[BUG] Task #4884662 for Kingdoms v1.9.1.3 generated an exception

### ISSUE THREAD

**Issue by Fargus5** [DevLan-Support/arvan#9]
[19:47:12]: [WARN] [Kingdoms] Task #4884662 for Kingdoms v1.9.1.3 generated an exception
java.lang.ClassCastException: class org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState cannot be cast to class org.bukkit.block.Chest (org.bukkit.craftbukkit.v1_16_R2.block.CraftBlockState and org.bukkit.block.Chest are in unnamed module of loader 'app')
at org.kingdoms.managers.ProtectionSignsManager.lambda$doubleChestProtectNotifier$5(ProtectionSignsManager.java:381) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-246]
at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-246]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-246]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-246]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-246]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-246]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-246]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by Fargus5** [comment]
fixed
